@startuml
!pragma layout elk
skinparam classFontSize 14
!define LIGHTORANGE
skinparam groupInheritance 1
skinparam componentStyle uml2
skinparam wrapMessageWidth 100
skinparam ArrowColor #Maroon

title Archiefbank ontology - 0.4 - 2022-02-11 10:18:49 +0100
              
package abv {

class Aangroei{
	{field} xsd:string : id 
	{field} rdf:langString : waarde 
	{field} abv:Aangroei : trefwoord 
}
Aangroei - "1" Aangroei : trefwoord >
Aangroei --|> Codetabel

class Adres{
	{field} xsd:string : id 
	{field} xsd:string : straat_en_nummer 
	{field} abv:Plaats : gemeente 
}
Plaats - "1" Adres : gemeente >

class Agent{
	{field} xsd:string : id 
	{field} abv:Identificatienummer : identificatie 
	{field} rdf:langString : naam 
	{field} abv:Datering : datering 
	{field} xsd:string : datering_text 
	{field} rdf:langString : geschiedenis_agent 
	{field} abv:Taal : taal 
	{field} abv:Associatie : associaties 
	{field} abv:Publicatie : bronnen_agent 
	{field} abv:Publicatie : bibliografie_agent 
	{field} xsd:string : opmerking 
}
Identificatienummer -  Agent : identificatie >
Datering - "1" Agent : datering >
Taal -  Agent : taal >
Associatie - "1" Agent : associaties >
Publicatie -  Agent : bronnen_agent >
Publicatie -  Agent : bibliografie_agent >

class Archief{
	{field} xsd:string : id 
	{field} abv:Identificatienummer : identificatienummer 
	{field} rdf:langString : titel 
	{field} abv:Datering : datering 
	{field} xsd:string : datering_text 
	{field} abv:Beschrijvingsniveau : beschrijvingsniveau 
	{field} abv:Archief : is_onderdeel_van 
	{field} abv:Omvang : omvang 
	{field} abv:Samensteller : samensteller 
	{field} abv:Beheerder : beheerder 
	{field} rdf:langString : geschiedenis_archief 
	{field} rdf:langString : verwerving 
	{field} rdf:langString : inhoud_en_bereik 
	{field} abv:Waardering : selectie 
	{field} abv:Aangroei : aangroei 
	{field} xsd:string : aangroei_text 
	{field} abv:Ordening : ordening 
	{field} xsd:string : ordening_text 
	{field} abv:JuridischeBeperking : juridische_beperking 
	{field} abv:Raadplegingsvoorwaarde : raadplegingsvoorwaarde 
	{field} abv:Taal : taal 
	{field} xsd:string : taal_text 
	{field} abv:Publicatie : toegang 
	{field} abv:Publicatie : bronnen_archief 
	{field} abv:Publicatie : bibliografie_archief 
	{field} xsd:string : aantekening_archivaris 
	{field} abv:Associatie : associatie 
	{field} abv:Rechtenstatus : rechtenstatus_metadata 
	{field} xsd:string : bronverwijzing_record 
	{field} xsd:string : bronverwijzing_archief 
}
Identificatienummer -  Archief : identificatienummer >
Datering -  Archief : datering >
Beschrijvingsniveau - "1" Archief : beschrijvingsniveau >
Archief - "1" Archief : is_onderdeel_van >
Omvang -  Archief : omvang >
Samensteller -  Archief : samensteller >
Beheerder -  Archief : beheerder >
Waardering -  Archief : selectie >
Aangroei - "1" Archief : aangroei >
Ordening - "1" Archief : ordening >
JuridischeBeperking - "1" Archief : juridische_beperking >
Raadplegingsvoorwaarde -  Archief : raadplegingsvoorwaarde >
Taal -  Archief : taal >
Publicatie -  Archief : toegang >
Publicatie -  Archief : bronnen_archief >
Publicatie -  Archief : bibliografie_archief >
Associatie - "1" Archief : associatie >
Rechtenstatus - "1" Archief : rechtenstatus_metadata >

class Associatie{
	{field} xsd:string : id 
	{field} abv:Plaats : plaats 
	{field} abv:Agent : agent 
	{field} abv:Periode : periode 
	{field} abv:Onderwerp : onderwerp 
}
Plaats -  Associatie : plaats >
Agent -  Associatie : agent >
Periode -  Associatie : periode >
Onderwerp -  Associatie : onderwerp >

class Beheerder{
	{field} xsd:string : id 
	{field} abv:RolBeheerder : rol 
	{field} abv:Erkenning : erkenning 
	{field} abv:Adres : adres 
	{field} xsd:string : telefoon 
	{field} xsd:string : email 
	{field} xsd:string : website 
	{field} xsd:string : gebouw 
	{field} abv:Publicatie : toegang 
	{field} xsd:string : openingsuren 
	{field} xsd:string : toegangsvoorwaarden 
	{field} abv:Bereikbaarheid : bereikbaarheid 
}
RolBeheerder - "1" Beheerder : rol >
Erkenning - "1" Beheerder : erkenning >
Adres -  Beheerder : adres >
Publicatie -  Beheerder : toegang >
Bereikbaarheid -  Beheerder : bereikbaarheid >
Beheerder --|> Agent

class Bereikbaarheid{
	{field} xsd:string : id 
}

Bereikbaarheid --|> Codetabel

class Beschrijvingsniveau{
	{field} xsd:string : id 
}

Beschrijvingsniveau --|> Codetabel

class BibliografieArchief{
	{field} xsd:string : id 
}

BibliografieArchief --|> Concept

class Bronbeschrijving{
	{field} xsd:string : id 
}

Bronbeschrijving --|> Concept

class Bronverwijzing{
	{field} xsd:string : id 
}


class Codetabel{
	{field} xsd:string : id 
}

Codetabel --|> Concept

class Concept{
	{field} xsd:string : id 
	{field} abv:Identificatienummer : identificatienummer 
	{field} rdf:langString : label 
	{field} abv:TypeConcept : type 
	{field} rdf:langString : definitie 
}
Identificatienummer -  Concept : identificatienummer >
TypeConcept -  Concept : type >

class Contactpersoon{
	{field} xsd:string : id 
}

Contactpersoon --|> Agent

class Definitie{
	{field} xsd:string : id 
}

Definitie --|> Term

class Erkenning{
	{field} xsd:string : id 
}

Erkenning --|> Concept

class Functie{
	{field} xsd:string : id 
}

Functie --|> Codetabel

class FunctieBeroepActiviteit{
	{field} xsd:string : id 
}

FunctieBeroepActiviteit --|> Concept

class GeschiedenisAgent{
	{field} xsd:string : id 
}

GeschiedenisAgent --|> Term

class GeschiedenisArchief{
	{field} xsd:string : id 
}

GeschiedenisArchief --|> Term

class Identificatienummer{
	{field} xsd:string : id 
	{field} xsd:string : waarde 
	{field} abv:TypeIdentificatienummer : type 
	{field} abv:Agent : bron 
}
TypeIdentificatienummer - "1" Identificatienummer : type >
Agent - "1" Identificatienummer : bron >

class InhoudBereik{
	{field} xsd:string : id 
}

InhoudBereik --|> Term

class JuridischeBeperking{
	{field} xsd:string : id 
	{field} xsd:boolean : privacy_gevoelig 
	{field} xsd:boolean : contractuele_beperking 
	{field} xsd:boolean : gevoelig_voor_auteursrechtelijkebescherming 
}


class Label{
	{field} xsd:string : id 
}

Label --|> Term

class Naam{
	{field} xsd:string : id 
	{field} rdf:langString : waarde 
	{field} abv:TypeNaam : type_naam 
}
TypeNaam - "1" Naam : type_naam >
Naam --|> Term

class Omvang{
	{field} xsd:string : id 
	{field} rdf:langString : waarde 
	{field} abv:Taal : taal 
	{field} abv:Materiaalsoort : trefwoord 
}
Taal - "1" Omvang : taal >
Materiaalsoort -  Omvang : trefwoord >

class Onderwerp{
	{field} xsd:string : id 
}

Onderwerp --|> Codetabel

class Ordening{
	{field} xsd:string : id 
	{field} rdf:langString : waarde 
	{field} abv:Ordening : trefwoord 
}
Ordening - "1" Ordening : trefwoord >
Ordening --|> Codetabel

class Periode{
	{field} xsd:string : id 
}

Periode --|> Codetabel

class Plaats{
	{field} xsd:string : id 
	{field} abv:Identificatienummer : identificatienummer 
	{field} abv:Naam : plaatsnaam 
}
Identificatienummer -  Plaats : identificatienummer >
Naam -  Plaats : plaatsnaam >

class Publicatie{
	{field} xsd:string : id 
	{field} abv:Identificatienummer : identificatienummer 
	{field} xsd:string : bibliografische_verwijzing 
	{field} abv:Naam : auteur 
	{field} rdf:langString : titel 
	{field} xsd:string : reeks 
	{field} xsd:string : reeksnummer 
	{field} xsd:string : uitgever 
	{field} xsd:string : plaats_van_uitgave 
	{field} xsd:date : datum_uitgave 
	{field} xsd:anyURI : url 
}
Identificatienummer -  Publicatie : identificatienummer >
Naam -  Publicatie : auteur >

class Raadplegingsvoorwaarde{
	{field} xsd:string : id 
	{field} xsd:string : tekst 
	{field} abv:Taal : taal 
	{field} abv:Raadplegingsstatus : raadplegingsstatus 
}
Taal - "1" Raadplegingsvoorwaarde : taal >
Raadplegingsstatus - "1" Raadplegingsvoorwaarde : raadplegingsstatus >
Raadplegingsvoorwaarde --|> Term

class Rechtenstatus{
	{field} xsd:string : id 
}

Rechtenstatus --|> Codetabel

class Rol{
	{field} xsd:string : id 
}

Rol --|> Concept

class RolBeheerder{
	{field} xsd:string : id 
}

RolBeheerder --|> Codetabel

class RolSamensteller{
	{field} xsd:string : id 
}

RolSamensteller --|> Codetabel

class Samensteller{
	{field} xsd:string : id 
	{field} abv:RolSamensteller : rol 
	{field} abv:TypeAgent : type 
	{field} abv:Functie : functie_beroep_activiteit 
}
RolSamensteller - "1" Samensteller : rol >
TypeAgent - "1" Samensteller : type >
Functie -  Samensteller : functie_beroep_activiteit >
Samensteller --|> Agent

class Soort{
	{field} xsd:string : id 
}

Soort --|> Concept

class Taal{
	{field} xsd:string : id 
}

Taal --|> Codetabel

class Term{
	{field} xsd:string : id 
	{field} rdf:langString : waarde 
}


class Titel{
	{field} xsd:string : id 
}

Titel --|> Term

class Toegang{
	{field} xsd:string : id 
}


class TypeAgent{
	{field} xsd:string : id 
}

TypeAgent --|> Codetabel

class TypeIdentificatienummer{
	{field} xsd:string : id 
}

TypeIdentificatienummer --|> Codetabel

class TypeNaam{
	{field} xsd:string : id 
}

TypeNaam --|> Codetabel

class TypeVergelijking{
	{field} xsd:string : id 
}

TypeVergelijking --|> Codetabel

class TypeWaarde{
	{field} xsd:string : id 
}

TypeWaarde --|> Codetabel

class Vergelijking{
	{field} xsd:string : id 
	{field} rdf:langString : waarde 
	{field} abv:TypeVergelijking : type_vergelijking 
}
TypeVergelijking - "1" Vergelijking : type_vergelijking >
Vergelijking --|> Term

class Verwerving{
	{field} xsd:string : id 
}

Verwerving --|> Term

class Waarde{
	{field} xsd:string : id 
	{field} rdf:langString : waarde 
	{field} abv:TypeWaarde : type_waarde 
}
TypeWaarde - "1" Waarde : type_waarde >
Waarde --|> Term

class Waardering{
	{field} xsd:string : id 
	{field} xsd:string : waardestelling 
	{field} abv:Waarde : waarde 
	{field} abv:Vergelijking : vergelijking 
	{field} xsd:date : datum_waardering 
	{field} abv:Publicatie : bron_waardering 
	{field} abv:Agent : bijdragers 
	{field} xsd:string : opmerkingen 
}
Waarde -  Waardering : waarde >
Vergelijking -  Waardering : vergelijking >
Publicatie -  Waardering : bron_waardering >
Agent -  Waardering : bijdragers >

class Materiaalsoort{
	{field} xsd:string : id 
}

Materiaalsoort --|> Codetabel

class Datering{
	{field} xsd:string : id 
	{field} xsd:duration : gestructureerd 
	{field} xsd:string : beschrijving 
}


class Raadplegingsstatus{
	{field} xsd:string : id 
}

Raadplegingsstatus --|> Codetabel

class TypeConcept{
	{field} xsd:string : id 
}

TypeConcept --|> Codetabel

hide circle
hide methods
hide empty members
@enduml
          
